# Generated by Django 3.0 on 2020-01-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_measurements_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='date',
            new_name='date_time',
        ),
    ]
